name: mzi_e687e91e
settings:
  changed:
    bend:
      function: bend_euler
      settings:
        cross_section:
          function: cross_section
          settings:
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 1.0
        with_bbox: true
    cross_section:
      function: cross_section
      settings:
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1.0
    splitter:
      function: mmi1x2
      settings:
        cross_section:
          function: cross_section
          settings:
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 1.0
        width: 1.0
        width_mmi: 3
    straight:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 1.0
        with_bbox: true
  child: null
  default:
    bend:
      function: bend_euler
    combiner: null
    cross_section: strip
    cross_section_x_bot: null
    cross_section_x_top: null
    delta_length: 10.0
    length_x: 0.1
    length_y: 2.0
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter: mmi1x2
    straight:
      function: straight
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  full:
    bend:
      function: bend_euler
      settings:
        cross_section:
          function: cross_section
          settings:
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 1.0
        with_bbox: true
    combiner: null
    cross_section:
      function: cross_section
      settings:
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1.0
    cross_section_x_bot: null
    cross_section_x_top: null
    delta_length: 10.0
    length_x: 0.1
    length_y: 2.0
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter:
      function: mmi1x2
      settings:
        cross_section:
          function: cross_section
          settings:
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 1.0
        width: 1.0
        width_mmi: 3
    straight:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 1.0
        with_bbox: true
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  function_name: mzi
  info: {}
  info_version: 2
  module: gdsfactory.components.mzi
  name: mzi_e687e91e
