settings:
  changed:
    bend:
      function: bend_euler
      settings:
        cross_section:
          function: cross_section
          settings:
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 0.9
        decorator:
          function: add_pins
    cross_section:
      function: cross_section
      settings:
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 0.9
    decorator:
      function: add_pins
    splitter:
      function: mmi1x2
      settings:
        cross_section:
          function: cross_section
          settings:
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 0.9
        decorator:
          function: add_pins
        width: 0.9
    straight:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 0.9
        decorator:
          function: add_pins
  child: null
  default:
    bend:
      function: bend_euler
    combiner: null
    cross_section:
      function: cross_section
      settings: {}
    delta_length: 10
    length_x: 0.1
    length_y: 2
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter:
      function: mmi1x2
    straight:
      function: straight
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  full:
    bend:
      function: bend_euler
      settings:
        cross_section:
          function: cross_section
          settings:
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 0.9
        decorator:
          function: add_pins
    combiner: null
    cross_section:
      function: cross_section
      settings:
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 0.9
    decorator:
      function: add_pins
    delta_length: 10
    length_x: 0.1
    length_y: 2
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter:
      function: mmi1x2
      settings:
        cross_section:
          function: cross_section
          settings:
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 0.9
        decorator:
          function: add_pins
        width: 0.9
    straight:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            width: 0.9
        decorator:
          function: add_pins
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  function_name: mzi
  info: {}
  info_version: 2
  module: gdsfactory.components.mzi
  name: mzi_d502274f
version: 0.0.1
