settings:
  changed:
    cross_section:
      function: cross_section
      settings:
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1
    decorator:
      function: add_pins
  child: null
  default:
    angle: 90
    cross_section:
      function: cross_section
      settings: {}
    direction: ccw
    npoints: 720
    p: 0.5
    with_arc_floorplan: true
  full:
    angle: 90
    cross_section:
      function: cross_section
      settings:
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1
    decorator:
      function: add_pins
    direction: ccw
    npoints: 720
    p: 0.5
    with_arc_floorplan: true
  function_name: bend_euler
  info:
    dy: 10.0
    length: 16.637
    radius: 10.0
    radius_min: 7.061
    wg_width: 1.0
  info_version: 2
  module: gdsfactory.components.bend_euler
  name: bend_euler_5a3fc5a7
version: 0.0.1
