settings:
  changed:
    cross_section:
      function: cross_section
      settings:
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1
    decorator:
      function: add_pins
  child: null
  default:
    cross_section:
      function: cross_section
      settings: {}
    length: 10
    npoints: 2
  full:
    cross_section:
      function: cross_section
      settings:
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1
    decorator:
      function: add_pins
    length: 10
    npoints: 2
  function_name: straight
  info:
    length: 10.0
    width: 1.0
  info_version: 2
  module: gdsfactory.components.straight
  name: straight_5a3fc5a7
version: 0.0.1
