name: straight_f84cb6d2
settings:
  changed:
    cross_section:
      function: cross_section
      settings:
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1.0
  child: null
  default:
    cross_section: strip
    length: 10.0
    npoints: 2
    with_bbox: true
  full:
    cross_section:
      function: cross_section
      settings:
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1.0
    length: 10.0
    npoints: 2
    with_bbox: true
  function_name: straight
  info:
    cross_section:
      function: cross_section
      settings:
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1.0
    function_name: cross_section
    length: 10.0
    settings:
      add_pins:
        function: add_pins
      bbox_layers:
      - - 36
        - 0
      bbox_offsets:
      - 3
      layer:
      - 34
      - 0
      width: 1.0
    width: 1.0
  info_version: 2
  module: gdsfactory.components.straight
  name: straight_f84cb6d2
