settings:
  changed:
    cross_section:
      function: cross_section
      settings:
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1
    decorator:
      function: add_pins
    width: 1
    width_mmi: 3
  child: null
  default:
    cross_section:
      function: cross_section
      settings: {}
    gap_mmi: 0.25
    length_mmi: 5.5
    length_taper: 10
    taper:
      function: taper
    width: 0.5
    width_mmi: 2.5
    width_taper: 1
  full:
    cross_section:
      function: cross_section
      settings:
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 1
    decorator:
      function: add_pins
    gap_mmi: 0.25
    length_mmi: 5.5
    length_taper: 10
    taper:
      function: taper
    width: 1
    width_mmi: 3
    width_taper: 1
  function_name: mmi1x2
  info: {}
  info_version: 2
  module: gdsfactory.components.mmi1x2
  name: mmi1x2_3898ed20
version: 0.0.1
